spring:
  application:
    name: order-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: "jdbc:postgresql://localhost:5435/orders_db"
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql

kafka:
  bootstrap:
    server: localhost:9092, localhost:9093
  topic:
    order-created: order_created
    order-updated: order_updated
    order-deleted: order_deleted

s3:
  key-id:
  key-secret:
  region: ru-central1
  bucket-name: npv90-learning-java-bucket
  folder: learning
  endpoint: https://storage.yandexcloud.net